import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { guidePages } from "@/data/pages";
import { site } from "@/data/site";
import JsonLd from "@/components/JsonLd";
import { websiteSchema, videoGameSchema } from "@/lib/seo";
export const metadata:Metadata={alternates:{canonical:"/"}};
export default function Home(){return <><JsonLd data={[websiteSchema(),videoGameSchema()]}/><section className="hero-home"><Image src="/gameplay-town-wide.png" alt="Little Troubles in Spooky Town title screen" fill priority sizes="100vw" className="object-cover object-center"/><div className="hero-shade"/><div className="page-shell hero-content"><div className="max-w-4xl"><p className="hero-eyebrow">Independent player companion</p><h1>Little Troubles<br/>in Spooky Town</h1><p className="hero-copy">Controller prompts on a keyboard? A float ability that will not jump? A missing barbell? Find a focused answer tied to Kenney’s published instructions.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/controls/" className="btn-primary">Find a control</Link><a href={site.officialUrl} className="btn-hero-secondary">Open official game</a></div></div></div></section><section className="page-section"><div className="page-shell"><div className="section-heading"><div><p className="eyebrow">Choose your problem</p><h2>Get back to the game</h2></div></div><div className="intent-grid">{guidePages.filter(p=>["controls","how-to-fly","find-the-missing-barbell","bugs-fixes"].includes(p.slug)).map(p=><Link key={p.slug} href={`/${p.slug}/`} className="intent-card tone-mint"><span><strong>{p.title}</strong><small>{p.description}</small></span></Link>)}</div></div></section><section className="page-section task-band"><div className="page-shell article-body"><h2>What this guide covers</h2><p>Kenney’s official release supports HTML5, Windows and Linux. Our reference covers published controls, specific developer answers and troubleshooting. It does not claim a full walkthrough or an optimal quest order.</p><p>The earlier full-task route contained unsupported details and has been withdrawn. Read the <Link href="/updates/">source and correction log</Link> for the scope of this revision.</p><p>Editorial identity: Hlele. Research review: Codex agent. No human playtest is claimed.</p></div></section></>}
